### ISSUE TITLE
No instructions for running notebook

### ISSUE THREAD

**Issue by eculler** [eriktuck/lst-crop-stress-capstone#6]
Users attempting to reproduce your analysis need detailed instructions on how to run your code.

You do not include a command for running your  analysis. There are a couple things a user needs to know:

- What notebook to run? There are a LOT of notebooks here.
- How to run jupyter notebook or jupyter lab, or some alternative

Note that your environment.yml does not contain juypter lab or jupyter notebook, so even someone familiar with running notebooks might not be able to run yours interactively. They could still use the jupyter run command...but that would require instructions as well for most people.

**Comment by eriktuck1** [comment]
added link to Jupyter documentation
